language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  #- hhvm
  # hhvm: https://github.com/facebook/hhvm/issues/5335 (not in hhvm 3.6.6 yet)
  # hhvm 3.11 supports this: https://3v4l.org/50NU6

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
