language: php

php:
  - 5.4
  - 5.5
  - 5.6
  # - hhvm
  # hhvm bug: https://github.com/facebook/hhvm/issues/5335

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
